### ISSUE TITLE
How to use rpc interface of your public test net?

### ISSUE THREAD

**Issue by qiluge** [blockstack/blockstack-core#1054]
I'm sorry that I don't find the rpc guide document. And I'm not sure that if your public test net provides the rpc interface. If you like, please tell me about how to access your public test net. And how can I construct transaction that send some STX? Also how can I listen the STX deposit to my address?

**Comment by kantai** [comment]
Documentation on the public testnet is available here:

https://testnet.blockstack.org/

The API reference for blockstack-core (the RPC interface for mainnet and testnet) is here:

https://core.blockstack.org/

I'm closing this issue for now, since it's more of a question rather than a bug or feature request. Typically for questions and discussion, it's better to ask on forum.blockstack.org
