### ISSUE TITLE
How to create address and transfer?

### ISSUE THREAD

**Issue by ruanqunfeng** [blockstack/blockstack-core#1088]
And is there has rcp command lists?

**Comment by jcnelson** [comment]
You'll want to use the [CLI](https://github.com/blockstack/cli-blockstack) to generate an address and execute a transfer.

**Comment by ruanqunfeng** [comment]
> You'll want to use the [CLI](https://github.com/blockstack/cli-blockstack) to generate an address and execute a transfer.

I want to use code

**Comment by kantai** [comment]
I'd recommend using blockstack.js (https://github.com/blockstack/blockstack.js) if you want to interact with the network programmatically:

See: http://blockstack.github.io/blockstack.js/globals.html#transactions for the transaction generation functions.

Closing this issue for now, since it's not a blockstack-core issue.
