### ISSUE TITLE
move from text file DB to more manageable data store

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#11]

**Comment by jcnelson** [comment]
My stress tests indicate that we're probably going to be fine until we reach ~1 million names.  Then, we need to seriously look at a database.  Sqlite would probably work until we reach into the billions.

**Comment by shea256** [comment]
OK how about we plan on switching to sqlite next (whenever necessary)?

**Comment by muneeb-ali** [comment]
I think we can add SQLite support for the next version and flag this issue with the next release, which reminds me that what release numbers are we using? The last released version was blockstore-0.0.3 and @jcnelson and I have also been calling this release "1.0". It might make sense to call it v0.1.0 since this is the first production release and we will not be changing the genesis block after this release.

**Comment by jcnelson** [comment]
This is present in the `develop` branch, but will need to be sync'ed with the new stable release.

**Comment by jcnelson** [comment]
This will be available in 0.14.

**Comment by shea256** [comment]
Ha awesome this issue is from Dec 5, 2014. Excited for SQL :D

**Comment by jcnelson** [comment]
Been working on it off and on since I joined :)

**Comment by muneeb-ali** [comment]
@jcnelson next release meaning v0.14 correct? As in this is already done?

**Comment by jcnelson** [comment]
Yup! Closing this issue.
