### ISSUE TITLE
Unclarity in Clarity Reference

### ISSUE THREAD

**Issue by moxiegirl** [blockstack/blockstack-core#1205]
@njordhov commented on [Mon Dec 23 2019](https://github.com/blockstack/docs.blockstack/issues/480)

Several entries in the [Clarity reference ](https://docs.blockstack.org/core/smart/clarityref) includes a sentence construct like:

    The .... function attempts to ‘unpack’ the ... argument

See the entries for [default-to](https://docs.blockstack.org/core/smart/clarityref#default-to), [expects](https://docs.blockstack.org/core/smart/clarityref#expects) and [expects-err!](https://docs.blockstack.org/core/smart/clarityref#expects-err). For example:

> The default-to function attempts to ‘unpack’ the second argument: if the argument is a (some ...) option, it returns the inner value of the option. If the second argument is a (none) value, default-to it returns the value of default-value.`

It is not clear what 'unpack’ means. The quotes suggest it's an introduced concept. Here are some suggested starting points for a revision:

> The default-to function returns the contained value of the second argument, or the value of the first argument if the second argument is `none`.

or

> If the second argument is an [optional type](https://docs.blockstack.org/core/smart/clarityref#some) returns the contained value of the second argument; If the second argument  is [none](https://docs.blockstack.org/core/smart/clarityref#none) returns the value of the first argument.

---

@moxiegirl commented on [Thu Dec 26 2019](https://github.com/blockstack/docs.blockstack/issues/480#issuecomment-569172996)

@njordhov Thanks for issue. I'll look into clarifying this with the dev team.

**Comment by moxiegirl** [comment]
@njordhov The reference is generated from the `develop` branch. I've moved the issue there and I'll correct it there.

**Comment by moxiegirl** [comment]
@jcnelson Can you clarify the word unpack here. It seems like the system is traversing a tree --- is this related to MARF?

**Comment by jcnelson** [comment]
Clarity supports limited algebraic data types -- in particular, it has an `(optional A)` type and a `(response A B)` type.  An `(optioanl A)` type can either be `(some A)` or `(none)`, and a `(response A B)` type can either be `(ok A)` or `(err B)`.  For example, `(some u3)` and `(none)` would have type `option<uint>`, and `(ok \"woot!\")` and `(err 'false)` would have type `result<(buff 5), bool>`.

To "unpack" one of these algebraic data types means to extract one of the "inner" types.  Unpacking an `(optional A)` means to do something to get at `A`, and unpacking `(response A B)` means to do something to get at ether `A` or `B` (where "do something" is specific to the function doing the unpacking).

For example, consider `unwrap!`:
* `(unwrap! (optional A) B)` will return `A` if `(optional A) is `(some A)`, or will return `B` if `(optional A)` is `(none)`
* `(unwrap! (response A B) C)` will return `A` if `(response A B)` is `(ok A)`, or will return `C` if `(response A B)` is `(err B)`.

Here, `unwrap!` "unpacks" something that has an algebraic data type in a particular way -- specifically, it extracts `A` in the `(some A)` and `(ok A)` cases.

The built-in functions that "unpack" an algebraic data type each behave differently.  For example, `unwrap-err!` "unpacks" a `(response A B)` by extracting `B` if `(response A B)` is `(err B)`.

Because the algebraic data types we support each have two variants (e.g. `(some ...)` or `(none)`; `(ok ...)` or `(err ...)`), the built-in "unpacking" functions need to be told how to handle each variant.  Some, like `unwrap!`, simply evaluate to either one of the contained types of the algebraic data type, or they return something else.  Others, like `match`, will "unpack" the algebraic data type into its different variants and evaluate a different code body on the thing(s) they contained, depending on which variant was unpacked.

Does that help clarify things?

**Comment by moxiegirl** [comment]
@jcnelson Thanks, that does help. I'll work something up to explain this in docs...and also to clarify the reference.

**Comment by moxiegirl** [comment]
@jcnelson the `unwrap` functions do not appear in the latest `develop` branch. I've modified your comment and will ask you to review that.
