### ISSUE TITLE
Profile missing from the indexed profile data

### ISSUE THREAD

**Issue by sdsantos** [blockstack/blockstack-core#1258]
My user profile (`sdsantos.id.blockstack`) is missing from https://storage.googleapis.com/blockstack-search_indexer_data/profile_data.json

There might be others missing too, but mine is they only one I couldn't find.

**Comment by jcnelson** [comment]
Hey, thanks for reporting this!  We'll try and figure out why this is happening.

**Comment by jcnelson** [comment]
@kantai Some background -- I dug into our search indexer logs and it looks like it's overloading the Core node we use for fetching name and profile info.  Is there a way to throttle back the profile-crawling parts so it does a tunable number of requests/sec?

**Comment by diwakergupta** [comment]
@jcnelson is this the right repo for this issue?

**Comment by jcnelson** [comment]
Yes -- this is where the search indexer lives

**Comment by kantai** [comment]
This repo would probably be more appropriate:

https://github.com/blockstack/blockstack-search-indexer

**Comment by kantai** [comment]
This profile is now included in the search index:

https://core.blockstack.org/v1/search?query=sdsantos.id.blockstack

The search index currently takes much longer to process updates than it used to, since there are > 1million names to index, and it was really designed for closer to 50k. I'm closing this issue for now, since the profile is now being correctly indexed. If we want to speed up the indexing time, we can open a new issue over on https://github.com/blockstack/blockstack-search-indexer

**Comment by sdsantos** [comment]
Is the index now covering 100% of the total accounts, or is there any idea of what percentage is missing?

**Comment by kantai** [comment]
Yes -- it covers all accounts at the time the batch was started. Accounts that may have had an error during the batch lookup (e.g., invalid profiles) won't be included.
