### ISSUE TITLE
put_profile fails with "Invalid previous profile hash"

### ISSUE THREAD

**Issue by stiell** [blockstack/blockstack-core#240]
When calling `put_profile` on http://node.blockstack.org:6264/RPC2 (via `blockstack set_profile`) I've been getting `{"error": "Invalid previous profile hash"}`, despite the provided hash matching the profile returned from an immediately preceding `get_profile` call.

This seems to have been caused by two different versions of the profile being on the network at the same time, and possibly different servers handling the `get_profile` and `put_profile` calls.

If the point of the hash check is to avoid an attacker replacing a profile with an older version, I'd suggest using a timestamp rather than a hash of the previous profile. That way a legitimate client can update the profile even if there is an inconsistency between servers or if the old profile data is not available.

**Comment by jcnelson** [comment]
Hi @stiell, I have done some initial work on this.  You are right--we want to stop attackers from uploading old versions of the profiles.  We didn't go with timestamps at first since we were worried about clock skew, but in relying on a signature over the previous hash, we were assuming that there is a data store holding your last profile that will correctly serve it on request.  Normally this is the case--the client keeps a copy on your computer.  But as you point out, this leads to problems if there is inconsistency across the set of replicas.  This will be fixed in 0.14.
