### ISSUE TITLE
Decide APIv1 endpoints

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/blockstack-core#279]
My understanding is that APIv1 endpoints are pretty much decided (in offline discussions). I'm documenting the current state here.

@jcnelson said on Slack 

```
endpoints are:
* registering a name: `POST /api/v1/names` with JSON payload `{'name': '...'}`
* transferring a name to an address:  `PUT /api/v1/names/:name/owner` with JSON payload `{'owner': '...'}`
* getting the state of all pending transactions:  `GET /api/v1/blockchain/bitcoin/pending`
* getting all names owned by an address: `GET /api/v1//addresses/:address/names`
* getting the address of a name, as well as its zonefile: `GET /api/v1/names/:name`
* getting the address of the owner and wallet of the blockstack node: `GET /api/v1/node/wallet/public
```

I'd also like to identify the **must-haves** from **nice-to-have**, so we can focus on the import endpoints first.

**Comment by shea256** [comment]
As far as I can tell, this list is correct.

Here is my assessment of the must haves and nice-to-haves...

Must haves for v0.3:

* registering a name: `POST /api/v1/names` with JSON payload `{'name': '...'}`
* getting all names owned by an address: `GET /api/v1/addresses/:address/names`
* getting the address of a name, as well as its zonefile: `GET /api/v1/names/:name`
* getting the address of the owner and wallet of the blockstack node: `GET /api/v1/node/wallet/public

Nice to haves for v0.3:

* getting the state of all pending transactions:  `GET /api/v1/blockchain/bitcoin/pending`
* transferring a name to an address:  `PUT /api/v1/names/:name/owner` with JSON payload `{'owner': '...'}`

**Comment by shea256** [comment]
@larrysalibra please correct me if I'm wrong and I'm missing something.

**Comment by shea256** [comment]
OK @larrysalibra and I just had a discussion about the API endpoints, including what their current status is, what we need for this release, and what we can push off to next release. Here are the prioritized endpoints for the next two releases.

#### For v0.3 on February 12th

| Method  | API Call | Payload | Returns |
| ------------- | ------------- | ------------- | ------------- |
| Register name | POST /v1/names | {"name": NAME, "zonefile": ZONEFILE, "owner_address": OWNER_ADDRESS } | { "success": true } |
| Get name info | GET /v1/names/{name} | - | { "address": ADDRESS, "zonefile": ZONEFILE, "registered": true } | 
| Get address info | GET /v1/address/{address} | - | { "names": [] } |
| Get wallet address | GET /v1/wallet/address | - | { "address": ADDRESS } |
| Get name price | GET /v1/prices/names/{name}  | - | { "total_price": PRICE, "registered": false } |

#### For v0.4 on February 26th

| Method  | API Call | Payload | Returns |
| ------------- | ------------- | ------------- | ------------- |
| Get pending transactions | GET /v1/blockchain/bitcoin/pending | - | { "transactions": [] } |

@larrysalibra @muneeb-ali @jcnelson please take a look and let's discuss how we can move forward on these and what the status is for each one.

For the v0.3 release, we're going to push off the search endpoint and fall back to the API online. We'll be integrating the new search endpoint in v0.4.

Also, @jcnelson can we remove the "/api" prefix at the beginning of each endpoint so that all endpoints start with the version number, as shown above?

**Comment by larrysalibra** [comment]
Looks good to me.

Just to clarify:

`GET /v1/wallet/address` should return the **payment address** of the blockstack core wallet.

`POST /v1/names` should be the equivalent of running `blockstack register`, `blockstack update`, `blockstack transfer` operations on the command line.

`GET /v1/names/{name}`  Including `registered: true` seems redundant in the response: ```{ "address": ADDRESS, "zonefile": ZONEFILE, "registered": true }```. We can return `404` if the name doesn't exist.

**Comment by shea256** [comment]
Update:

We're shooting for a flow where we can spend unconfirmed UTXOs.

This will allow us to achieve an experience where the user can deposit bitcoin to Core's wallet address and then immediately register a name.

Jude mentioned that we just need our UTXO provider to indicate the unconfirmed UTXO's.

**Comment by jcnelson** [comment]
Sample outputs:

**`POST /v1/names`**
```
{
   "transaction_hash": "..."
}
```

**`GET /v1/names/{name}`**
```
{
   "status": "..."  # "registered" or "revoked"
   "zonefile": "..."  # raw zonefile text
   "zonefile_hash": "...",
   "address": "..."  # the owner's address
   "last_txid": "..."  # the txid of the last transaction to affect the name
}
``` 

**`GET /v1/addresses/{address}`**
```
{
   "names": [...]   # the list of names (strings)
}
```

**`GET /v1/wallet/payment_address`**
```
{
   "address": "..."
}
```

**`GET /v1/wallet/owner_address`**
```
{
   "address": "..."
}
```

**`GET /v1/prices/{name}`**
```
{
    "name_price": {
        "btc": 0.001, 
        "satoshis": 100000
    }, 
    "preorder_tx_fee": {
        "btc": 0.0009659, 
        "satoshis": 96590
    }, 
    "register_tx_fee": {
        "btc": 0.0009269, 
        "satoshis": 92690
    }, 
    "total_estimated_cost": {
        "btc": 0.00456098, 
        "satoshis": 456098
    }, 
    "update_tx_fee": {
        "btc": 0.00166818, 
        "satoshis": 166818
    }
}
```
(this is identical to the output from `blockstack price`).

**`GET /v1/blockchain/bitcoin/pending`**
```
{
   "queues": {
      "preorder": {
         [
             "name": "...",
             "tx_hash": "...", 
             "confirmations": "..."
         ],
         ...
      },
      "register": {
         [
             "name": "...",
             "tx_hash": "...", 
             "confirmations": "..."
         ],
         ...
      },
      "update": {
         [
             "name": "...",
             "tx_hash": "...", 
             "confirmations": "..."
         ],
         ...
      },
      "transfer": {
         [
             "name": "...",
             "tx_hash": "...", 
             "confirmations": "..."
         ],
         ...
      },
   }
}
```
(The above queue names ("preorder", "register", "update", "transfer") map to lists with one or more items.  If the queue is empty, then it will be absent from the returned JSON document).

**Comment by larrysalibra** [comment]
Thanks @jcnelson ! This helps a lot! For `"confirmations": "..."` in the pending queues, is that the number of confirmations? If so, is it an number or a string?

**Comment by jcnelson** [comment]
It's the number of confirmations, as an int.  Will update the comment.

**Comment by muneeb-ali** [comment]
Great to see the discussion here. We can move the API outputs to a README when it's finalized.

**Comment by jcnelson** [comment]
Need to update `POST /v1/prices/{name}` to include the transfer fee too.

**Comment by larrysalibra** [comment]
> Need to update POST /v1/prices/{name} to include the transfer fee too

It's `GET /v1/prices/names/{name}` right?

**Comment by larrysalibra** [comment]
@jcnelson For the `POST /v1/names` output, is the `transaction_hash` the transaction id of the preorder transaction?

**Comment by larrysalibra** [comment]
Also want to clarify `GET /v1/addresses/{address}`: Our current implementation takes a comma-seperated list of addresses:

https://api.blockstack.com/v1/addresses/1EXwrz2E3WvxhdeRB1ArKtdE5NKtKC7Edx,1JQGg1WxBmEmEckricyfNAiXfwfWQakvRL,1BoYYokpHxH2y7UdEqFqAp6rRU6aiQ28mH,1CRstWU2h74uetyhDQKELuRF3Z9zdLJVde,17TCvFZiTkFZ2NKSJT9KTrw6oD2dbByRFd,1NBQFb1cFzchBH4mQN7FqSF8EryL1S1iSH,1D7wFkEbG5pZ98j1pYfj7Ru3XtokMsmYat,1Hz1akWgTbfmVGvvWq3YdpQf7RRyQK1hZH,1HZRZRdFcfBrErYY59CVLXyitH82ph1b9h,1Gb5tfKXC2JUCbBHc52vQnQ9yQii3AX7Tz,1P2DTnkVpAqBhoE5pr6oM9SLwWfefFCXgC,14zDxenKdCtGDFH3kLdqwZc8QpgZub4kYw,1NT5hcZ6PBEhccC7nSLejuUuYDV55w8pJ3,15mb1xJmTWz1M7pfdVC8mCkPv76TDQLzUN,19Po3xuq1WKdnV5JfPAUB3kqEbzKow7xTh,1LUwMARXYj1GDaDsQePUeJVLW4jJocYs9q,1LMWdike8MNfZtnkkgbV7f1WDhdt7ukHVP,1CAS2Vn4TyJoS5j9Bmt3WwsCiMcN1q1FzP,1ApAPEEK2qJJ7z3o2tCr8s52VcPQBei9rQ,1KuSqLfng2XBHczvKhfkoVnXumZa1WtCtE,187C1oqQPgZg5n6Pm5x8LesJ6EYeu6XFiR,16uYuaiYwmHYNcAxUnLZtnbqa3s18BzqtD,1NC9B1A2kWgpXgUkkGqqzmpP42ztTPuQXD,1HPBbznDfnbrxw8xAXgCSeRwBr9qaXQgGM,18tQb38PbBJ14BLSKbSMh5aeRfqBotfHyD,147YCsagfG4cuXxpxK6WPmeWPfqDH7Hq3c,178WC1wsPXqgPW843zaNnTmZUbLMAiNsxk,1EPKSYJqBmEBr6bDXSTcuJyNAFxn7srkHb/names

And returns:

```
{
  "results": [
    {
      "address": "1EXwrz2E3WvxhdeRB1ArKtdE5NKtKC7Edx",
      "names": [
        "devname2.id",
        "devname3.id",
        "devname4.id"
      ]
    },
    {
      "address": "1JQGg1WxBmEmEckricyfNAiXfwfWQakvRL",
      "names": []
    },
    {
      "address": "1BoYYokpHxH2y7UdEqFqAp6rRU6aiQ28mH",
      "names": []
    },
    {
      "address": "1CRstWU2h74uetyhDQKELuRF3Z9zdLJVde",
      "names": []
    },
    {
      "address": "17TCvFZiTkFZ2NKSJT9KTrw6oD2dbByRFd",
      "names": []
    },
    {
      "address": "1NBQFb1cFzchBH4mQN7FqSF8EryL1S1iSH",
      "names": []
    },
    {
      "address": "1D7wFkEbG5pZ98j1pYfj7Ru3XtokMsmYat",
      "names": []
    },
    {
      "address": "1Hz1akWgTbfmVGvvWq3YdpQf7RRyQK1hZH",
      "names": []
    },
    {
      "address": "1HZRZRdFcfBrErYY59CVLXyitH82ph1b9h",
      "names": []
    },
    {
      "address": "1Gb5tfKXC2JUCbBHc52vQnQ9yQii3AX7Tz",
      "names": []
    },
    {
      "address": "1P2DTnkVpAqBhoE5pr6oM9SLwWfefFCXgC",
      "names": []
    },
    {
      "address": "14zDxenKdCtGDFH3kLdqwZc8QpgZub4kYw",
      "names": []
    },
    {
      "address": "1NT5hcZ6PBEhccC7nSLejuUuYDV55w8pJ3",
      "names": []
    },
    {
      "address": "15mb1xJmTWz1M7pfdVC8mCkPv76TDQLzUN",
      "names": []
    },
    {
      "address": "19Po3xuq1WKdnV5JfPAUB3kqEbzKow7xTh",
      "names": []
    },
    {
      "address": "1LUwMARXYj1GDaDsQePUeJVLW4jJocYs9q",
      "names": []
    },
    {
      "address": "1LMWdike8MNfZtnkkgbV7f1WDhdt7ukHVP",
      "names": []
    },
    {
      "address": "1CAS2Vn4TyJoS5j9Bmt3WwsCiMcN1q1FzP",
      "names": []
    },
    {
      "address": "1ApAPEEK2qJJ7z3o2tCr8s52VcPQBei9rQ",
      "names": []
    },
    {
      "address": "1KuSqLfng2XBHczvKhfkoVnXumZa1WtCtE",
      "names": []
    },
    {
      "address": "187C1oqQPgZg5n6Pm5x8LesJ6EYeu6XFiR",
      "names": []
    },
    {
      "address": "16uYuaiYwmHYNcAxUnLZtnbqa3s18BzqtD",
      "names": []
    },
    {
      "address": "1NC9B1A2kWgpXgUkkGqqzmpP42ztTPuQXD",
      "names": []
    },
    {
      "address": "1HPBbznDfnbrxw8xAXgCSeRwBr9qaXQgGM",
      "names": []
    },
    {
      "address": "18tQb38PbBJ14BLSKbSMh5aeRfqBotfHyD",
      "names": []
    },
    {
      "address": "147YCsagfG4cuXxpxK6WPmeWPfqDH7Hq3c",
      "names": []
    },
    {
      "address": "178WC1wsPXqgPW843zaNnTmZUbLMAiNsxk",
      "names": []
    },
    {
      "address": "1EPKSYJqBmEBr6bDXSTcuJyNAFxn7srkHb",
      "names": []
    }
  ]
}
```

There's the potential for weird things to happy as we approach the maximum URL length which varies per browser.

I'm going to assume 1 address per request as listed above and have the portal make a separate request for each address instead of providing multiple addresses on the url.

**Comment by jcnelson** [comment]
> It's GET /v1/prices/names/{name} right?

Yes; fixed comment.

> Also want to clarify GET /v1/addresses/{address}: Our current implementation takes a comma-seperated list of addresses:
> I'm going to assume 1 address per request as listed above and have the portal make a separate request for each address instead of providing multiple addresses on the url.

Ah, I didn't know that.  Thanks for letting me know.  I'll update our REST interface to do this as well.

Regarding maximum URL length, we can just limit the number of addresses to e.g. 10 per call.  The smallest maximum URL length I'm aware of is 2048 characters.  What do you all think?

**Comment by larrysalibra** [comment]
@jcnelson I wouldn't worry about supporting multiple addresses per request at this time.

I already re-implemented the browser portal to assume one 1 address per request. If a portal's identity wallet has multiple addresses, the portal makes multiple requests. We don't have address rotation enabled in the portal at the moment anyways.

I see this more of an optimization than a must have for this release. We can revisit handling multiple requests in the future.

**Comment by jcnelson** [comment]
@shea256 @larrysalibra Regarding `POST /v1/names`, do we also want to pass in a profile?  The code is already written to take one; by default, we put in an empty profile.  Maybe the arguments could be:

```
{"name": NAME, "zonefile": ZONEFILE_STRING, "owner_address": OWNER_ADDRESS, "profile": PROFILE_OBJECT }
```

**Comment by larrysalibra** [comment]
@jcnelson What's the benefit of passing a profile? In the portal, we already generate a blank profile, upload it to dropbox, generate a public url, and create the zonefile with the url.

While the registration process is happening, users can update the profile -- add their name, upload pictures, etc -- in the portal.

This is currently what the portal sends to `POST /v1/names`:

```
{ name: 'larry3.id', owner_address: '1CrSPTcX6BsvLwMm6eYkvk2f3U5y5Yic2u', zonefile: '$ORIGIN larry3.id\n$TTL 3600\n_http._tcp\tIN\tURI\t10\t1\t"https://www.dropbox.com/s/fl2gickklkwppbk/profile.json?dl=1"\n\n' }
```

**Comment by jcnelson** [comment]
Ah, I didn't know the browser was storing the profile.  That works too.

**Comment by shea256** [comment]
@larrysalibra @jcnelson Just catching up on this conversation around address rotation. Yeah for now one address per request makes sense.

And I do like @jcnelson's idea to move towards 10 per request in the future.

**Comment by larrysalibra** [comment]
@shea256 agree. I went with 1 address per request in this version because I wasn't sure (when I posted the original comment) what the core would support in this version since our doc only specified 1 addres. Didn't want to risk assuming the api would accept multiple addresses and then find out at the last minute it wouldn't.

**Comment by jcnelson** [comment]
@larrysalibra @shea256 One thing to keep in mind about `POST /v1/names` is that the `zonefile` should have the data public key in it.  You should encode the public key as a `TXT` record, as follows:

`pubkey TXT "pubkey:data:04cabba0b5b9a871dbaa11c044066e281c5feb57243c7d2a452f06a0d708613a46ced59f9f806e601b3353931d1e4a98d7040127f31016311050bedc0d4f1f62ff"`

Without this key, the identity API in the desktop specs won't work.

**Comment by shea256** [comment]
@jcnelson OK cool will make sure that is included. I assume this is not strictly necessary but it's being required from now on because we want to have users explicitly provide signing keys. Is that correct?

Can we alternatively supply an address instead of a public key? Currently in the identity and auth libraries we allow identities to be set as addresses and then public keys can be supplied later to prove they correspond 1-to-1.

Also, when we do use public keys, can we focus on compressed public keys and sunset the uncompressed ones?

**Comment by jcnelson** [comment]
> @jcnelson OK cool will make sure that is included. I assume this is not strictly necessary but it's being required from now on because we want to have users explicitly provide signing keys. Is that correct?

Yes.  The data keypair is your identity's root key.  Your personas, accounts, and data stores will all be signed with hardened children of the root private key, so your zone file needs to have your root public key.

> Can we alternatively supply an address instead of a public key? Currently in the identity and auth libraries we allow identities to be set as addresses and then public keys can be supplied later to prove they correspond 1-to-1.

I'd need to think about this more (need to test it), but it should be possible.

> Also, when we do use public keys, can we focus on compressed public keys and sunset the uncompressed ones?

That's the plan.  `rc-0.14.1` automatically decompresses them as needed (since `fastecdsa` only works with uncompressed keys).

**Comment by shea256** [comment]
> Yes. The data keypair is your identity's root key. Your personas, accounts, and data stores will all be signed with hardened children of the root private key, so your zone file needs to have your root public key.

Awesome. Then later we can introduce the "encryption" key. That's the only reason I started calling it the signing key instead of the data key.

Also, when you say root key, do you mean that we'd put extended public keys in the zone file instead of regular keys (aka `xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpiaQL2jkwSB1icqYh2cfDfVxdx4df189oLKnC5fSwqPfgyP3hooxujYzAu3fDVmz`)? Because I actually think that's where we need to go in the long term, just didn't think we were there yet in terms of support. Might be something we want to push off if it's going to be too complex for now.

> I'd need to think about this more (need to test it), but it should be possible.

Yeah it is, here's how I implemented it in the blockstack profiles library: https://github.com/blockstack/blockstack-profiles-py/blob/master/blockstack_profiles/token_verifying.py#L18. It's a bit of a quick and dirty implementation but it works.

> That's the plan. rc-0.14.1 automatically decompresses them as needed (since fastecdsa only works with uncompressed keys).

Awesome!

**Comment by jcnelson** [comment]
> Also, when you say root key, do you mean that we'd put extended public keys in the zone file instead of regular keys (aka xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpiaQL2jkwSB1icqYh2cfDfVxdx4df189oLKnC5fSwqPfgyP3hooxujYzAu3fDVmz)? Because I actually think that's where we need to go in the long term, just didn't think we were there yet in terms of support. Might be something we want to push off if it's going to be too complex for now.

Actually, the code is mostly implemented.  Your master private key gets used to generate your persona keypairs (as hardened children), and a persona private key gets used to generate an account keypair (as a hardened child).  In both cases, the public keys are replicated to your storage providers as mutable data.

> Yeah it is, here's how I implemented it in the blockstack profiles library: https://github.com/blockstack/blockstack-profiles-py/blob/master/blockstack_profiles/token_verifying.py#L18. It's a bit of a quick and dirty implementation but it works.

Right now, we can verify profiles and mutable data using either a public key or an address (since in both cases we include the public key in payload).  However, there are lots of cases where we use the data public key from a remotely-fetched zone file.  I need to go through and verify that we can deprecate that behavior in favor of using a data public key address.

**Comment by muneeb-ali** [comment]
@shea256 @jcnelson @larrysalibra is all the information from here captured in the [current version of the API spec](https://github.com/blockstack/blockstack-core/blob/master/api/README.md)?

If yes, then we can go ahead and close this issue. I'll wait for signoff from everyone.

**Comment by muneeb-ali** [comment]
I'm keeping this issue open because we need to iron out the profile/user endpoints.

**Comment by muneeb-ali** [comment]
The initial version of the API is now there and most endpoints are defined. Closing this issue.

I'll open a new issue for the user/profile endpoints which need more work.
