### ISSUE TITLE
Prepare the Blockstack REST API for quick setup

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-core#286]
@jcnelson and I just went through setting up the Blockstack REST API.

I'm using this issue to document the issues that we came across that need to be addressed for a programmatic setup:

- [ ] `blockstack rpcctl start` should be available without advanced mode turned on
- [ ] `blockstack rpcctl start` should not prompt the user to enter an email address
- [ ] `blockstack rpcctl start` should work without requiring a change to the `client.ini` file ("authenticate_api = false" could be set as the default)

---

Afterwards, @muneeb-ali and @jcnelson and I discussed a way that we could make the setup commands simple while still preserving the independence of Blockstack core from clients that communicate with it.

Here's an interface we came up with that should be work well:

```
blockstack setup
blockstack start api --key=be22dbf4305f45e082ce2e36d090968c2aacd712
```

The first command sets up the wallet while the second command starts the REST API.

Would love @larrysalibra's thoughts on this as well.

**Comment by muneeb-ali** [comment]
The interface

```
blockstack setup
blockstack start api --key=be22dbf4305f45e082ce2e36d090968c2aacd712
```

looks great to me. Also, glad that we were able to discuss the role of Blockstack Core process and (external) clients/systems.

**Comment by larrysalibra** [comment]
```
blockstack setup
blockstack start api --key=be22dbf4305f45e082ce2e36d090968c2aacd712
```
I like the general direction.

Would `blockstack setup` take a wallet password or other parameters? If not, why the additional command?

Would `blockstack api start --key=be22dbf4305f45e082ce2e36d090968c2aacd712` (`blockstack api stop` `blockstack api status` etc) be more consistent with how other commands behave? (eg. `service apache2 start`)

---

Not sure this is the thread to bring this up: With regards to advanced mode. I'm not sure why we have this mode. In my view, if someone is using the command line interface, they're already "advanced" - If we're looking to not confuse people by showing them too many commands they may not need to know about, we could make it so that running `blockstack` or `blockstack --help` shows only the "basic" commands and that running something like `blockstack --help-advanced` shows info about the other commands. That there's state around which arguments are accepted on the command line makes it confusing to help people. I can't just say run `blockstack get_name_blockchain_record larry.id` - I need to first ask them to make sure they have advanced mode enabled.

**Comment by shea256** [comment]
You're right, it should probably be something more like this:

```
blockstack setup --password=be22dbf4305f45e082ce2e36d090968c2aacd712
blockstack api start --password=be22dbf4305f45e082ce2e36d090968c2aacd712
```

**Comment by jcnelson** [comment]
@larrysalibra Thanks for your input!  The reason we have "advanced mode" is because we want to treat a set of commands as stable versus unstable.  As in, the commands that are not in "advanced mode" are guaranteed to stay the same across releases.  The commands in "advanced mode" are experimental and may change their behavior or disappear entirely across releases.

Regarding the interface, do we want to differentiate between the wallet password and the API password?  Maybe something like this?

```
blockstack setup --password=... --api_secret=...
blockstack api start --password=... --api_secret=...
blockstack api stop
blockstack api restart --password=... --api_secret=...
```

**Comment by shea256** [comment]
@jcnelson Isn't it the case that for the wallet setup command only the wallet password is needed while for the api commands only the API secret is needed?

**Comment by jcnelson** [comment]
Yes; edited.

**Comment by larrysalibra** [comment]
Checking up on the status of this:

It looks like the current quick setup api is this:

`blockstack --config ~/git/blockstack-core/config/client.ini init --password password`
`blockstack --config ~/git/blockstack-core/config/client.ini set_advanced_mode on`
`blockstack --config ~/git/blockstack-core/config/client.ini rpcctl start --password password`

I also had to set `authenticate_api` to `False`

I ran into a `{"error": "Failed to connect to backend"}` problem when trying to connect an API endpoint. Not sure if you're still working on things @jcnelson - let me know if you want me to open an issue.

--

@shea256 A challenge with this quick setup api is that we won't know which password the user wants to use for the blockstack-core bitcoin wallet until after the API is running.  I plan to workaround this by having the Mac app generate a random password on first run, storing it in the user's macOS keychain, and providing that password to blockstack core when starting the api.

**Comment by jcnelson** [comment]
@larrysalibra can you show me your `api_endpoint.log` file?

**Comment by larrysalibra** [comment]
@jcnelson sure: ```
127.0.0.1 - - [11/Feb/2017 17:32:45] "GET /v1/names/larry8.id HTTP/1.1" 500 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/registrar.py", line 864, in run
    queue_cleanall( path=self.queue_path, config_path=self.config_path )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 558, in queue_cleanall
    cleanup_preorder_queue(path=path, config_path=config_path)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 392, in cleanup_preorder_queue
    rows = queuedb_findall("preorder", path=path)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 181, in queuedb_findall
    db = queuedb_open(path)
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 82, in queuedb_open
    con = queuedb_create( path )
  File "/Users/larry/git/blockstack-core/venv/lib/python2.7/site-packages/blockstack-0.14.1-py2.7.egg/blockstack_client/backend/queue.py", line 68, in queuedb_create
    con = sqlite3.connect( path, isolation_level=None )
OperationalError: unable to open database file

127.0.0.1 - - [11/Feb/2017 17:43:29] "GET /v1/names/larry8.id HTTP/1.1" 500 -
127.0.0.1 - - [11/Feb/2017 17:43:31] "GET /v1/names/larry8.id HTTP/1.1" 500 -
127.0.0.1 - - [11/Feb/2017 17:43:32] "GET /v1/names/larry8.id HTTP/1.1" 500 -
```

**Comment by jcnelson** [comment]
Thanks.  Will push a fix

**Comment by jcnelson** [comment]
Is this working now?

**Comment by larrysalibra** [comment]
Yes. It works well and is already integrated into the macOS app. Thank you so much for your help @jcnelson !

We can close this issue. (I don't have permission to manage issues on this repo)

**Comment by muneeb-ali** [comment]
@larrysalibra I added you. Want to test it out by closing the issue?

**Comment by larrysalibra** [comment]
Closed
