### ISSUE TITLE
API addition to get current key(s) for verifying ID-linked signatures

### ISSUE THREAD

**Issue by csuwildcat** [blockstack/blockstack-core#405]
**What we're building:**

We are working on a service that dispatches a payload for signing to one or multiple users. These users then sign the payload with whatever key is associated with their blockchain-anchored ID. The service needs to verify the signed payload when it receives it back to ensure it is signed buy the user ID that was intended.

**What we need:**

We would like a simple API method that returns the latest public key(s) a user has associated with their ID.

**Comment by csuwildcat** [comment]
@waynevaughan @grempe I filed this after talking with the Blockstack folks this morning; they have agreed to add something to support our use-case.

**Comment by jcnelson** [comment]
I'm taking a crack at adding a `blockstack get_name_public_key` command that will work on any name.  I stand by what I said earlier about wanting to use the public key in the zone file (and not the one from the blockchain) for the following reasons:
* a name is not guaranteed to have an on-chain public key
   * a name whose last operation is `NAME_REGISTRATION` or `NAME_TRANSFER` will have an unknown public key, since it will not yet have been revealed (i.e. the only data derived from the public key on-chain will be the hash contained in the relevant `scriptPubKey` output script)
   * a name owned by a `p2sh` script will have multiple public keys, and it is not obvious which one we should use.  Similar to the above, the public keys are only revealed once the owner sends a transaction with them.
* we are moving to a model where zone files all but require a public key, specifically because we need to make sure anyone can look it up
   * Gaia already requires a zone file public key to work (there's no way around this)
   * Hermes will also require a zone file public key to authenticate messages

If you want to support something like this without requiring well-formed zone files, then the best we can do is support looking up a name's public key hash.  This hash is guaranteed to be present in the blockchain regardless of a name's zone file contents (either as the multisig redeem script hash or the single public key hash), and we can prefer the hash of the name's zone file public key over the hash of the public key(s) in the blockchain when deciding which hash to return.

Let me know what you want me to do.

**Comment by csuwildcat** [comment]
What I would like to do most of all is nail down a location where a known public key will always reside that all external services should use to verify data. I feel this should be codified in the name rooting protocol we create in the DIF.

**Comment by jcnelson** [comment]
We can guarantee that the name zone file, if well-formed, will have a public key in a well-defined location (i.e. a `TXT` record named `pubkey`).  This will be true regardless of which blockchain is used to host the name.

**Comment by csuwildcat** [comment]
Great, let's map the command to that and document it so people start relying on it as the go-to key/location for this sort of thing! :)

**Comment by shea256** [comment]
One option is to use the address as the signature verifier instead of the public key. This means that you can verify a signature against an address even if the public key associated with it has not been revealed.

**Comment by jcnelson** [comment]
Merged to `rc-0.14.2`:

Example: get a public key:
```bash
$ blockstack get_public_key judecn.id
{
    "public_key": "04cabba0b5b9a871dbaa11c044066e281c5feb57243c7d2a452f06a0d708613a46ced59f9f806e601b3353931d1e4a98d7040127f31016311050bedc0d4f1f62ff"
}
```

Example: set a public key
```
$ blockstack update judecn.id
--------------------------------------------------------------------------------
Data public key: 04cabba0b5b9a871dbaa11c044066e281c5feb57243c7d2a452f06a0d708613a46ced59f9f806e601b3353931d1e4a98d7040127f31016311050bedc0d4f1f62ff

Profile replicas (4):
(1) file:///home/jude/.blockstack/storage-disk/mutable/judecn.id
    Handled by drivers: [disk]
(2) https://blockstack.s3.amazonaws.com/judecn.id
    Handled by drivers: [s3,blockstack_resolver,http]
(3) http://node.blockstack.org:6264/RPC2#judecn.id
    Handled by drivers: [blockstack_server,http]
(4) dht+udp://fc4d9c1481a6349fe99f0e3dd7261d67b23dadc5
    Handled by drivers: [dht]

What would you like to do?
(a) Add profile URL
(b) Remove profile URL
(c) Swap URL order
(d) Set or change public key
(e) Save zonefile
(f) Do not save zonefile

Selection: d
New ECDSA public key (empty for None): 03ff5b2964d0498b7b810615f3761742d23db7db1c554b7d30d9e4abc891a667f9
--------------------------------------------------------------------------------
Data public key: 04ff5b2964d0498b7b810615f3761742d23db7db1c554b7d30d9e4abc891a667f96ddf18bbb1d26af5db9788743c292f0dceb65dbcfec2bca2be0eb49f76d6318b

Profile replicas (4):
(1) file:///home/jude/.blockstack/storage-disk/mutable/judecn.id
    Handled by drivers: [disk]
(2) https://blockstack.s3.amazonaws.com/judecn.id
    Handled by drivers: [s3,blockstack_resolver,http]
(3) http://node.blockstack.org:6264/RPC2#judecn.id
    Handled by drivers: [blockstack_server,http]
(4) dht+udp://fc4d9c1481a6349fe99f0e3dd7261d67b23dadc5
    Handled by drivers: [dht]

What would you like to do?
(a) Add profile URL
(b) Remove profile URL
(c) Swap URL order
(d) Set or change public key
(e) Save zonefile
(f) Do not save zonefile

Selection: e
{
    "success": true,
    "transaction_hash": "f576313b2ff4cc7cb0d25545e1e38e2d0d48a6ef486b7118e5ca0f8e8b98ae45",
    "message": "The name has been queued up for registration and will take a few hours to go through. You can check on the status at any time by running 'blockstack info'."
}
```

**Comment by grempe** [comment]
Will there be any option for including a public key for encryption use? Or will keys be limited to ECDSA `secp256k1` signing keys?  There are use cases that @csuwildcat , @waynevaughan and I discussed that require encryption in addition to signing.

Also, I am curious if the reason for choosing the `secp256k1` curve was intentional for an interoperability reason? It is a choice which some might find controversial for general purpose (non-bitcoin) cryptography (instead of say, Curve25519 or ed25519).

http://safecurves.cr.yp.to/
http://blog.bettercrypto.com/?p=1004

**Comment by shea256** [comment]
@grempe You can include any key you want in the zone file. That includes keys for Bernstein curves, RSA keys, etc.

**Comment by grempe** [comment]
Thx @shea256, I understand that the zone file is an open container that we can include most anything in. Which of course can be a double-edged sword.

I suppose the question is more about what key types will be included for *all* users that create accounts (if any)? The problem with the add your own (of any alg, curve, byte form) approach is that that the keys will end up being...  any alg, any curve, any form. And as I understand, with no labels to mark what 'public_key' represents. This makes it tough to rely on those keys being found in a known location in a form that can be useful by applications built on this stack.

It's of course fine if you're not in the business of being a PKI, just as long as it is understood by those of us who may need to build something on top of that infrastructure that we will be responsible for the the creation, storage, retrieval, and consumption of those keys end-to-end. So end users would need to generate keys, manage the private key, and get the pub key into your zone file in a known location on their own.

Do you think that is a fair characterization?

**Comment by shea256** [comment]
@grempe OK fair. What would your ideal system look like? Would you like the primary key to be something other than an ECDSA key? Or would you like clear specification of keys in the zone file with set and get functions in the libraries?

**Comment by grempe** [comment]
Thanks for asking. I think have a set/get function to retrieve the keys from a know location is a good idea. In addition...

`// being handwavy partial wishlist`

*Every* ID gets:

- two keypairs generated, a signing keypair, and an encryption keypair.
- Optional: the keypairs are generated from a passphrase converted to a long deterministic seed via a KDF so you don't have to manage private key files, but instead enter a passphrase which, through a strong KDF like `scrypt` or `argon2` creates those keys in memory on the fly. Would allow use on multiple machines, impossible to lose private key. Key rotation is trickier though.
- the public keys are stored in a known location in the zone file, and marked with a tag which indicates what kind of key it is and how it is serialized. e.g.

```
{
    "pubkey_sig": "MHhERUFEQkVFRg==",
    "pubkey_sig_type": "ed25519",
    "pubkey_enc": "MHhCRUVGREVBRA=="
    "pubkey_enc_type": "x25519-xsalsa20-poly1305",
}
```

The tags allow software to determine which encryption/signing alg to use for the binary key material that is presented. Its important of course that implementations in different langs can consume those binary keys directly.

Keys are urlsafe Base64 encoded version of the binary byte array form of the key (only 33% larger than the binary form, as opposed to hex which is 2x the byte size).

The descriptive tag could also be included by prepending, with a delimiter like a colon, to a Base64 encoded version of the binary key. e.g. `ed25519:MHhERUFEQkVFRg==` if you wanted to save the whole thing in a single key.

I would not personally choose secp256k1 (aka bitcoin crypto) as the primitives for signing unless it is needed for some interoperability. If you really want ECDSA perhaps use it with a curve considered safer by the wider academic cryptography community which apparently considers secp256k1 questionable or unsafe depending on who you ask. For info on an implementation of those encryption types that I referenced for examples see:

https://github.com/dchest/tweetnacl-js
https://tweetnacl.cr.yp.to/tweetnacl-20140917.pdf
https://en.wikipedia.org/wiki/Argon2
https://en.wikipedia.org/wiki/Scrypt

If you wanted to see an example of what I was talking about with using the KDF to generate keys deterministically, see for example:

https://github.com/grempe/session-keys-js

And while I'm at it, something to anchor your keys from a PKI trust perspective would be nice (too bad its not ready for prime time yet):

https://security.googleblog.com/2017/01/security-through-transparency.html

If *every* blockstack ID had these keys available to them for both signing and encryption, at a well known property in the zonefile, and with a key type that is self-documenting and can be changed over time without breaking older zone files, I think you open up a lot of use cases.

**Comment by csuwildcat** [comment]
Might want to look at the DID/DDO spec for some of this, as it incorporates
many of these needs/processes for key handling, proofs, and signatures:
https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/master/topics-and-advance-readings/did-spec-working-draft-03.md

**Comment by grempe** [comment]
@csuwildcat I've read the DID/DDO spec and I noted the following:

The document seems to only indirectly take a position on the storage of keys, differentiating between signature and encryption keys, or which cryptographic algorithms to use for signing or encryption.

Section 5.12. Signature (Required) states that the DDO is required to be signed with a valid JSON-LD signature and that the DDO must have a signature block like:

```
{
    "signature": {
        "type": "LinkedDataSignature2015",
        "created": "2016-02-08T16:02:20Z",
        "creator": "did:76d0cdb7-9c75-4be5-8e5a-e2d7a35ce907/keys/1",
        "signatureValue": "QNB13Y7Q9oLlDLL6AHyL31OE5fLji9DwJSA8qnv81oRaKonij8m+Jv4XdiEYvJ97iRlzKU/92/0LafSL5JftEgl960DLcbqMFxOtbAmFOIMa7eDcrgTL5ytXeYCYKLjHQG3s8a3UKDKRuEK54qK1G5hGKGoLgAVa6xgcDLjW7M19PEJV/c3HpGA7Eez6VFMoTt4yESjZvOXC97xN3KpshOx2HT/btgUbo0XjA1Oi0QHdgrLcUsQGt6w23RjeSToalrsA1G69OFeN2OiQrz9Jb4561hvKLSyWObwRmS6n5Vgr5xkvUm6MONRq0Vg33kXevoVM64KTBkISul61tzjn4w=="
    }
}
```
So this implies the use of JSON-LD signatures. The latest document (that I am aware of) that describes linked data signatures is:

https://w3c-dvcg.github.io/ld-signatures/#signature-suites

Which takes pains to describe the metadata for a signature, but does not specify a signature suite (other than using RSA as the example).

I looked for actual implementations of JSON-LD signatures (something we are interested in using for Chainpoint proofs) and that implementation, in Javascript, can use `RSA` or `EcdsaKoblitzSignature2016` keypairs. `EcdsaKoblitzSignature2016` was only added last month and they previously called it `BitcoinSignature2016`. They appear to be using the [CoMakery/bitcore-message](https://github.com/CoMakery/bitcore-message) implementation of that signature algorithm to test against.

https://github.com/digitalbazaar/jsonld-signatures

Appendix Section A.2 (Verification Keys) provides the start of an example related to Sovrin which uses `ed25519` signing keys. They do Base58 encoding (instead of the Base64 I showed in my example above).

So the bottom line is that I don't see, at least in the docs I have reviewed, any strong opinions on:

* signing or encryption key algorithms
* how to encode keys
* how to identify keys
* how to make keys available (e.g. a specific property name)

Crypto is hard.

**Comment by csuwildcat** [comment]
@grempe I talked with @talltree (Drummond) at EICC and he told me the current DID draft doesn't include some of the additions to DDOs they're working on. He said they've been considering the addition of specific key semantics that would allow devs to reliably know which key should be used for a certain well known purpose, and where it is located in the DDO.

**Comment by jackzampolin** [comment]
Closing this as stale. Reopen if closed in error.
