### ISSUE TITLE
Improve configuration endpoints

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-core#420]
**Initial setup**

It would be nice to be able to start the API without having to first run the `blockstack setup` step. 
It seems like this is something that the API could do automatically for us at start up.

** Calling setup with -y **
Not a big deal, but a bit annoying for scripts --  calling setup with -y should kill the e-mail sign up prompt.

**Remote Configuration**

Users should be able to see how their Core node is configured and modify that configuration via the API.

**UTXO Provider Configuration**

Core v0.14.2 exposes UTXOs through the `/v1/blockchains/{blockchain_name}/{addr}/unspent`
Portal can use this instead of the getUtxo() function currently.

However, the configuration of UTXO providers in Core has strange interactions between 2 configuration settings (some of them due to defaults): `provider` and `url`. This led to issues on macOS when the default url pointed to an older provider. Fixing this would improve UTXO configuration.

**Comment by muneeb-ali** [comment]
+1 on no need for blockstack setup 

Same for the CLI setup. 

This is now in the 1.0 release milestone.

**Comment by jackzampolin** [comment]
We have made it possible to run this operation with scripts, and I don't think we are planning to provide configuration via endpoints right now. This work was going to be done to make core easier to drive from the browser. Because of the arch changes I'm going to go ahead and close this issue as resolved. Please reopen if necessary!
