### ISSUE TITLE
Registrar stops retrying after API endpoint restart

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#446]
We've seen a couple instances where name registrations have failed at the `NAME_TRANSFER` stage. (see https://github.com/blockstack/blockstack-browser/issues/504)

Our theory is that this is because bitcoin fees on the last transaction were so high as to be greater than the user's bitcoin balance.

The expected behavior of the registrar is to continue trying to send the `NAME_TRANSFER` transaction so that when the user deposits more bitcoin, the transaction will still suceed.

@jcnelson says:
> I'm looking at the transfer code.  I think the registrar gave up not because the queue is drained, but because of a logic error that stops the registrar from proceeding once restarted

**Comment by jcnelson** [comment]
The problem was that the registrar stops trying to act on previously-sent transactions after they have 130 confirmations.  For example, the presence of the `NAME_UPDATE` tells the registrar to send the `NAME_TRANSFER`, if there is one queued up afterwards.  If the `NAME_UPDATE` gets 130 confirmations, the registrar removes it, so it never acts on the missing `NAME_TRANSFER`.  This has been corrected in `rc-0.14.2-portal`.

**Comment by jcnelson** [comment]
This fix has been merged to `master` as part of the 0.14.2 release.

**Comment by kantai** [comment]
Closing this -- if it's still a problem we can reopen.
