### ISSUE TITLE
Component Architecture

### ISSUE THREAD

**Issue by jackzampolin** [blockstack/blockstack-core#565]
Moving discussion here from [this forum post](https://forum.blockstack.org/t/component-architecture/1417/19). 

The discussion has had two parts so far:

- [ ] A renaming of the current components to make them more user friendly
- [ ] Clarifying and consolidating where state is held in the different components

@larrysalibra @muneeb-ali @jcnelson @kantai @shea256

**Comment by jcnelson** [comment]
I'd recommend the "non-advanced" mode interface be preserved for the time being, until we hit 1.0.  There are parts of the infrastructure as well as a slew of users who currently rely on it.

**Comment by jackzampolin** [comment]
@jcnelson What do you mean by `non-advanced` mode? 

I was thinking we could likely make these changes as part of a `1.0` release or a longer running `1.0-beta` that gives users a chance to try the new interfaces before forcing them to switch.

**Comment by jcnelson** [comment]
When you install `blockstack`, you have to enable "advanced" method with `blockstack set_advanced_mode on`.  The non-advanced mode methods are the ones that are always available, and are also likely to be the most-used methods.

I'm not opposed to changing this--in fact, the plan is to get rid of "advanced mode" altogether.  Giving proper warning to users is a good idea.

**Comment by kantai** [comment]
Advanced mode was removed in 0.14.3, the feeling was that a CLI user was always in advanced mode.

Either way, I think this issue was meant to continue the architecture discussion from the forum post. But because this is a pretty open-ended topic (and one that is more of a long-term design plan), I think a forum discussion is a better venue for the discussion than a github issue.
