### ISSUE TITLE
Documentation: find out the set of API methods we need to preserve from blockstack_client

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#707]
The `blockstack_client` API service will persist, but the Python CLI will eventually be deprecated in favor of a Node.js CLI that uses functionality in `blockstack.js`.

We need to get a list of all of the methods in `blockstack_client` that we need to preserve in order to implement a stable API endpoint.

A cursory glance includes:

* everything in `blockstack_client/proxy.py`
* everything in `blockstack_client/zonefile.py`

**Comment by kantai** [comment]
This is a conservative list of the endpoints which are currently getting used by explorer, browser, or would be required for `blockstack.js` transaction generation.
* `GET /v1/names?page=X`
* `GET /v1/names/{name}`
* `GET /v1/names/{name}/history`
* `GET /v1/names/{name}/zonefile`
* `GET /v1/addresses/{blockchain}/{address}`
* `GET /v1/node/ping`
  * this should maybe return more information?
* `GET /v1/names/{name}/zonefile/{zoneFileHash}`
  * this should maybe be replaced with `GET /v1/zonefile/{zoneFileHash}`
* `GET /v1/prices/namespaces/{tld}`
* `GET /v1/prices/{name}`
  * this calls should probably change to only return the "op-fee" -- it currently tries to get the total cost breakdown of a registration. However, only the client can accurately estimate the transaction fees, because either the user chooses to pay lower fees, use a different tx service, or is using different kinds of addresses (single sig, multi-sig, segwit)
* `GET /v1/blockchains/{blockchainName}/consensus`
* `GET /v1/blockchains/{blockchainName}/name_count`
* `GET /v1/blockchains/{blockchainName}/operations/{blockHeight}`

The additional endpoint from PR #696 would be the only state-changing endpoint.
* `POST /v1/zonefile`

This endpoint, currently implemented in the flask app `/api` directory would be deprecated in favor of a simple node "resolver" service which just calls the `blockstack.lookupProfile` 
* `GET /v1/users/{name}`

**Comment by kantai** [comment]
This endpoint will need to be used as well:

`GET /v1/namespaces/id/`

**Comment by jcnelson** [comment]
This has been implemented in `feature/token-v1` and `feature/blockstack_client_refactor`
