### ISSUE TITLE
wire format documentation

### ISSUE THREAD

**Issue by rocky** [blockstack/blockstack-core#754]
I have been looking at https://github.com/blockstack/blockstack-core/blob/master/docs/wire-format.md

It looks like that with a few small changes, this could be reused with some generic changes as VM instructions for an on-chain VM interpreter.  (e.g. drop the consensus hash in each instruction, and use the magic once per sequence of instructions rather than once per instruction.) Personally, I think that would be helpful. 

*  the opcodes for `NAME_RENEWAL` and `NAME_REGISTRATION` both seem to be `:` and according
   to [blockstack/lib/config.py](https://github.com/blockstack/blockstack-core/blob/master/blockstack/lib/config.py#L433) this seems deliberate. I don't understand how the two are distinguished.
* magic doesn't seem to be described or its value defined. Is it a version number for the collection of instructions, and changes when the instruction set changes in any way? 
* Under `NAME_REGISTRATION`, there are two possible formats. Although one could look at the overall size of a transaction, a suggestion would be to use different opcodes to make things explicit rather than implicit (the size of the instruction). Doing this would allow bundling transactions, and would make it more straightforward to map this into a a corresponding VM instruction. 
* It would nice to give a description of what each operation does, even if one can figure this out say for `NAME_RENEWAL`, and  `NAME_REGISTRATION`. A link to other documentation would be fine. Even looking at the code, I'm not sure under what conditions `ANNOUNCE` would be used.

Is there any code that right now that decodes or encodes the wire format? (I see various places where the opcodes are used by config).

**Comment by jcnelson** [comment]
Hey @rocky, thanks for your feedback!

I agree with the points you make about the opcodes for a given transaction being ambiguous.  The reason the system does this is because at the time the wire format was agreed-upon, a key use-case we wanted to promote was to give users the ability to directly inspect their transactions in a blockchain explorer and see their name appear.  At the time, it was thought that having different opcodes for semantically-similar operations (e.g. multiple variations of registration and renewing) would lead to user confusion.

Now that the system has been in operation for a few years, it seems like this problem was overstated and that the VM implementation could be simplified by taking your recommendations (i.e. different opcodes for each operation, with no "opcode overloading" like it does today).

That said, let me see if I can answer your specific questions:

* A `NAME_RENEWAL` has a different set of outputs than a `NAME_REGISTRATION` (specifically, a `NAME_RENEWAL` has a burn address output and a `NAME_REGISTRATION` does not).  I agree that it is confusing that they have the same opcode.

* Magic is the bytes `id`.  I'll add that to the document.

* The two variations of `NAME_REGISTRATION` are distinguished by the fact that the former is required to be 40 bytes or less (and not to have 0-padding), whereas the latter is required to be more than 40 bytes.  I agree that using a different opcode would potentially make the VM implementation simpler.

* This sounds like it should be covered in this document: https://github.com/blockstack/blockstack-core/blob/feature/docs-bns/docs/blockstack_naming_service.md

You can find the code that decodes the wire-format in `blockstack.lib.operations.*`.  The code that encodes the wire format can be found in `blockstack_client.backend.operations.*` as well as in this feature-branch of `blockstack.js`: https://github.com/blockstack/blockstack.js/tree/feature/blockstack-operations/src/operations.  The long-term plan is to deprecate the `blockstack_client` package in favor of `blockstack.js`, since this is how the vast majority of users (i.e. non-CLI users) will generate their transactions.

**Comment by rocky** [comment]
Thanks @jcnelson for the information. 

> Magic is the bytes id

Still not understanding. Is the "id" unique then for each instruction? 

Other than that that clears everything up. If you want to close this feel free too. Or if you want to keep open and close with the commit that clarifies magic, that's cool too. 

Again, thanks.

**Comment by jcnelson** [comment]
> Still not understanding. Is the "id" unique then for each instruction?

No, magic is the bytestring `69 64`, which are the ASCII codes for the string "id".  Here's an example Blockstack transaction (note the decoded `OP_RETURN` at the bottom): https://www.blocktrail.com/BTC/tx/8b383b2e27a573b9d6205af677682cddf2d736bfdb8e56dfab0eefefc0c846eb.  The "magic" field in the wire format just makes it easier to filter out `OP_RETURN` outputs that are not meant for Blockstack.

**Comment by jcnelson** [comment]
Got the commit in; going ahead and closing this.  Please let me know if there are any other clarifications that need to be made!

**Comment by rocky** [comment]
All of the questions I previously had been cleared up with the clarifications - thanks.
