### ISSUE TITLE
API: Merge blockstack_client/rpc.py into blockstackd

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#774]
Move the RESTful API into blockstackd.  There will no longer be a `blockstack api start` command.  Instead, `blockstackd` will run both its back-plane RPC interface and the RESTful interface by default.

We will modify `blockstackd` so it can be started *without* the indexer, in order to preserve the semantics of `blockstack api start`.  It just might look different--probably like `blockstack-core start-api https://url.to.the.indexer.core.node.to.use` for starting just the RESTful interface instead of `blockstack-core start`.

**Comment by jcnelson** [comment]
CC @jackzampolin, who has good ideas on how to do this as painlessly as possible with respect to our deployments.

**Comment by jackzampolin** [comment]
One way to do this would be to fold the `blockstack api start` into the `blockstack-core start` command and then driving which interfaces are available through options in the configuration file. We would need to need to change the `Dockerfile` and the shape of our deployments if we do this, but it might be worth it for the simplicity gain. We could eliminate an entire component from most deployments allowing users to run them together, or split them apart when needed to handle scaling or network concerns.

If we maintain a `v0.19` branch and make the `Dockerfile` changes there we will have auto builds of the new image and I will be able to build and test the new architectures quickly. We are also moving deployments to `gcloud` so this would be a good time for a change like this.

Documentation and the integration test environment would need to be changed anyway so the additional time there would not be too large. I'm interested to hear what you think about that idea.

Alternately either of the above options work for me. I would prefer to pass the `https://url.to.the.indexer.core.node` param as a config option rather than as an arg however. 
r, or split them apart when needed to handle scaling or network concerns.

If we maintain a `v0.19` branch and make the `Dockerfile` changes there we will have auto builds of the new image and I will be able to build and test the new architectures quickly. We are also moving deployments to `gcloud` so this would be a good time for a change like this.

Documentation and the integration test environment would need to be changed anyway so the additional time there would not be too large. I'm interested to hear what you think about that idea.

Alternately either of the above options work for me. I would prefer to pass the `https://url.to.the.indexer.core.node` param as a config option rather than as an arg however.

**Comment by jackzampolin** [comment]
One way to do this would be to fold the `blockstack api start` into the `blockstack-core start` command and then driving which interfaces are available through options in the configuration file. We would need to need to change the `Dockerfile` and the shape of our deployments if we do this, but it might be worth it for the simplicity gain. We could eliminate an entire component from most deployments allowing users to run them together, or split them apart when needed to handle scaling or network concerns.

If we maintain a `v0.19` branch and make the `Dockerfile` changes there we will have auto builds of the new image and I will be able to build and test the new architectures quickly. We are also moving deployments to `gcloud` so this would be a good time for a change like this.

Documentation and the integration test environment would need to be changed anyway so the additional time there would not be too large. I'm interested to hear what you think about that idea.

Alternately either of the above options work for me. I would prefer to pass the `https://url.to.the.indexer.core.node` param as a config option rather than as an arg however.

**Comment by jcnelson** [comment]
I think there's value in making it so you can run the API process without the indexer process, since it takes a lot less disk space and network bandwidth.  Happy to make the API process read a config file to determine which Core node to contact.

I think this approach has the nice side-effect of not requiring us to change our deployments and documentation very much :)  Only the command syntax will change, but the semantics remain the same.

**Comment by jcnelson** [comment]
Update per our meeting:  The config file will determine the "profile" of the daemon---indexer, API, both.  If you want the API daemon, you add an API config section.  Same for the indexer.

**Comment by jcnelson** [comment]
This is now implemented in `feature/token-v1`

**Comment by jcnelson** [comment]
This is also implemented in `feature/blockstack_client_refactoring`, which does not break consensus.
