### ISSUE TITLE
Canonical Content Registry on Blockstack

### ISSUE THREAD

**Issue by denisnazarov** [blockstack/blockstack-core#79]
Hello, we are specifying a protocol for a canonical content registry. You can read a detailed proposal here: https://github.com/mine-code/canonical-content-registry. We are interested in building it on top of Blockstore to do the following:
1. Store unique CCID (canonical content identifier) in Blockstore
2. Append file instance metadata to CCID (see examples in [canonical-content-registry](https://github.com/mine-code/canonical-content-registry))
3. Tag a CCID with a nametag
4. Sign a [statement](https://github.com/openname/specifications/blob/master/profiles/profiles-v03.md#statements) stating a nametag belongs to an Openname profile
5. Append arbitrary metadata to CCID (hashtags, related CCIDs, etc)
6. Ability to easily interpret the above by a new node in the DHT

I wanted to open this issue to start a discussion about extending Blockstore to support writing metadata in the format above. What are the systems current limitations and what could be possible steps to extend blockstore?

Reading the README should provide some context. Let me know if I can clarify any of the ideas, and feel free to open CCR related issues on that repo.

@muneeb-ali @shea256 @jessewalden @moudy

**Comment by shea256** [comment]
This is awesome! Really like the detail you've added since you first showed us.

I'll dig into it deeper and provide some more in-depth feedback in a bit.

One quick thing I'm trying to figure out, though, is whether discussions like these should go under blockstore or under "specifications" for the protocol (the blockchain name protocol, formerly OpenName).

Check out the README.md:
https://github.com/openname/specifications

As you can see, we have specifications for users, but we can add specifications for content, according to your proposal.

Thoughts?

**Comment by denisnazarov** [comment]
I think definitely a good idea to eventually add to the spec repo. Not sure if the preliminary discussion belongs here, because it is around the technical limitations/possibilities of blockstore.

Still thinking through https://github.com/openname/blockstore/issues/81, will try to respond with some thoughts this weekend.

**Comment by shea256** [comment]
OK sounds good.

**Comment by muneeb-ali** [comment]
@denisnazarov Just read https://github.com/mine-code/canonical-content-registry -- great job at describing your system. Noticed you had Sybil attacks in the questions section. I'm writing about this and will share more details with you shortly. You might not have to worry about Sybil attacks :-)

**Comment by jackzampolin** [comment]
Closing as stale.
