### ISSUE TITLE
blockstack-core search endpoint returns empty results intermittently

### ISSUE THREAD

**Issue by prabhaav** [blockstack/blockstack-core#793]
After speaking to @kantai, it seems like the caching needs to be reduced on `https://core.blockstack.org/v1/search?query=` endpoint to help with the specific failures.

**Comment by jcnelson** [comment]
Do you know how often you're requesting queries?  It might also be a rate-limiting issue.

**Comment by prabhaav** [comment]
Every time a new contact is searched, and depending on the length of the name and speed at which they enter the name...maybe 3-4 times a name?

**Comment by jcnelson** [comment]
@kantai was this issue addressed, or does this have to do with the way we build our search index still?

**Comment by kantai** [comment]
This is related to the batch process we use currently -- The issue's severity was reduced by reducing the cache setting on the search results. The other route we could go (as a hotfix) is to build the mongo tables up and then rename them so that the "empty time" is closer to a second rather than 30 seconds. I can look into addressing this later in the week if its still a major pain point.

**Comment by kantai** [comment]
This should now be corrected in commit (https://github.com/blockstack/blockstack-core/commit/dd1aa516584f7b2a130c0ef5198511df315f12f1). I'm going to close this out, and if it appears to still be an issue, we can reopen.
