### ISSUE TITLE
Use a "real" search engine on profile and application state

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#802]
Expand the backend of the profile search endpoint to use a "real" search engine like Elasticsearch to build up indexes over profiles (and eventually app-specific state).  Needs to be easy to test and easy to deploy.

**Comment by vsund** [comment]
Curious whether there are ways to use @jackzampolin's indexer for this :)

Would probably need a dockerized microservice deployment of Core (which I'm not sure whether we need this yet).

**Comment by digitalwaveride** [comment]
Based on a discussion that we had in the forum: https://forum.blockstack.org/t/how-would-something-like-a-forum-page-work-on-blockstack/5216/6

It could be really beneficial to any app in the social media space, if Blockstack would provide an “indexer”. Minimising the amount of search queries will be a classic challenge for any application that has to deal with larger user networks and want to show curated user content or user feeds. It would help apps in that space to get off the ground much faster.
If such indexer are part of a professional node distribution via Blockstack, things might be also more reliable, the overall user experience should be better.

In order to keep apps that really care about privacy and independence out of this, maybe developers could opt-in if they want their apps to be indexed, per default they would be not part of the index.
Additionally such an index might be handy for Blockstack in the context of running the AppStore, and get stats etc. out of it.

**Comment by kantai** [comment]
Related issue: https://github.com/blockstack/gaia/issues/117

Should we close this one in favor of that?

**Comment by jcnelson** [comment]
Fine by me.  Closing in favor of https://github.com/blockstack/gaia/issues/117
