### ISSUE TITLE
Try test net (Larry)

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#822]
Please spend a day trying out the [Stacks testnet](https://testnet.blockstack.org). Record your experience, including what you tried and any issues you encountered in this ticket. If you found issues you believe should be addressed, please open a new issue and link it in your issue.

**Comment by larrysalibra** [comment]
Installation instructions reference the wrong branch of blockstack.js: https://github.com/blockstack/blockstack-core/issues/828

**Comment by larrysalibra** [comment]
Unable to check balance with cli: https://github.com/jcnelson/cli-blockstack/issues/5#issuecomment-391547718

**Comment by larrysalibra** [comment]
I find having the same address format for both bitcoin and stacks confusing.

**Comment by larrysalibra** [comment]
@jcnelson I find the fact that a bitcoin address represents all of the token types confusing.

I understand technically why that works. I think from a product and user experience perspective it makes more sense to use different address formats for the different token types.

There are a number of reasons for this. One reason is that without its "own" format like ethereum has it's own `0x` format, it doesn't seem like a full blown separate coin.

Another reason is to avoid user confusion. A bitcoin address is a bitcoin address. If i want to ask someone for the account to which they'd like to send me Stacks, do I ask them for a bitcoin address? How can someone looking at the string determine if the wallet software that generated supports stacks or only bitcoin?

**Comment by jcnelson** [comment]
Ah, I see what you mean.  I'm definitely in favor of making the Stacks account identifier Stacks-specific.  I agree that we should use a format that does not get confused with an existing cryptocurrency---the account identifier format should be Stacks-specific.

That being said, I have no strong opinions on what exactly the format will be.  Do you have any suggestions?  The only thing that might have been a good idea but we *cannot* do is change the address version to make the first character `S`, since we're already using those for subdomain addresses in DIDs.  However, anything else is fine with me.

**Comment by Anastik** [comment]
What about using a “$” at the front of each address? It might give off the wrong impression, but it still kind of uses the “S” and it easily denotes that it’s financial in nature. Could even be “$tx” or something along those lines.

**Comment by jcnelson** [comment]
@Anastik Nice idea, but we want to avoid country-specific money identifiers.  `$` is pretty US-centric.

@larrysalibra Want to open this problem as a separate issue?
