### ISSUE TITLE
`subdomain_count` is not the same as the number of results from getting all subdomains

### ISSUE THREAD

**Issue by hstove** [blockstack/blockstack-core#870]
@vrepsys (developer of theblockstats.com) let me know that the number returned from `subdomains_count` is not the exact same as the number collected by iterating over all subdomains.

This is probably related to https://forum.blockstack.org/t/local-blockstack-node-shows-incorrect-subdomain-count/5869/3 , and perhaps it only needs core.blockstack.org to run the fixed described in the forum.

I'm just adding this here for visibility, if it's no longer an issue, feel free to close.

**Comment by jcnelson** [comment]
A couple things --

* I don't remember if we updated core.blockstack.org to include the fix for this.
* There is a separate issue I discovered related to this -- a fast-sync'ed node can omit subdomains discovered by the source node if the zone file that contains them was recently discovered but not yet processed.  The fast-sync'ed node will think the zone file was already processed, when in fact it was not.  This should be fixed in `hotfix/fast-sync-subdomain-queue`.

The fix in both cases is straight-forward:
* stop the Core node
* blow away `~/.blockstack-server/subdomains.db`
* start the Core node

This will cause the Core node will re-build the subdomain database from scratch (it takes about 5 minutes on my laptop).

**Comment by jcnelson** [comment]
This is now merged to `master`, and we have since repaired core.blockstack.org.

**Comment by jcnelson** [comment]
@hstove I haven't seen this happen in our production network for the past week (once that fix got deployed).  Can we close this issue?

**Comment by jcnelson** [comment]
I think this has been fixed for a while now.  Closing here; please re-open if it's still broken.
