### ISSUE TITLE
Inter-contract callable functions with unrestricted return types

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-core#948]
Implement something like a `define-function-readonly` native function with the following features:
* Prohibited from mutating data - this check is performed during launch analysis. 
* Callable from other contracts. 
* Can return values of any type. 

This allows contracts to use helper functions on other contracts. 

This is currently only possible by creating a `define-public` function which stores the intended return value in a data map. The calling contract must then invoke the function, then retrieve the value with `fetch-contract-entry`.

**Comment by kantai** [comment]
Yeah -- this seems like a useful feature.

An alternative is adding a function

```
(contract-call-readonly ...)
```

Which can call normal, non-public functions, but any side-effects are always aborted.

**Comment by jcnelson** [comment]
I think that a `call-contract-readonly` method is less desirable than `define-public-readonly` because it creates more developer surprise.  `define-public-readonly` indicates to both the smart contract developer and any upstream consumers that this method cannot mutate state.  `call-contract-readonly` only indicates to upstream consumers that the method cannot mutate state.

**Comment by kantai** [comment]
In the case of `call-contract-readonly`, the _function_ wouldn't abort on changes, just the changes themselves would simply never commit on the database -- so you can call whatever you want, including `contract-call!`, `insert-entry!`, `set-entry!`, etc., it's just that any changes would never commit.

Either way seems fine to me.

**Comment by jcnelson** [comment]
> In the case of call-contract-readonly, the function wouldn't abort on changes, just the changes themselves would simply never commit on the database -- so you can call whatever you want, including contract-call!, insert-entry!, set-entry!, etc., it's just that any changes would never commit.

That still sounds like it has the potential to be a bag full of nasty surprises, and significantly degrades the predictability of smart contracts.  `insert-entry!` and `set-entry!` should always either mutate the table, or cause the contract to abort.  They should not be turned into no-ops by a hypothetical `call-contract-readonly` method somewhere far away in the call graph.

**Comment by kantai** [comment]
> The addition of call-contract-readonly means that a smart contract developer needs to reason about the behavior of their public functions under two different incompatible sets of invariants. This makes their life harder.

This is always the case -- an outer call can always return false and any inner calls mutations will be aborted.

**Comment by jcnelson** [comment]
But with `contract-call-readonly`, there are two different ways a function can run successfully (whether the developer likes it or not).  `define-public-readonly` does not have this problem.

**Comment by kantai** [comment]
> But with contract-call-readonly, there are two different ways a function can run successfully (whether the developer likes it or not).

Using `define-public-readonly` is fine by me.

But it doesn't make this true:

> insert-entry! and set-entry! should always either mutate the table, or cause the contract to abort.

Because outer public functions can choose to abort.

**Comment by jcnelson** [comment]
Sorry, I didn't characterize the behaviors of `insert-entry!` and `set-entry!` correctly.  But the point I was trying to make is that these functions have well-defined semantics and well-defined pre- and post-conditions, and they all involve mutating an underlying table (but they don't cause the execution to abort -- my bad).

Adding `contract-call-readonly` alters the semantics of these functions.  What this means is that a function that calls `set-entry!`, `insert-entry!` and/or `delete-entry!` will have different semantics based on whether or not it was called within a `contract-call-readonly` function -- the _call graph_ determines the behavior of the function, _in addition_ to the function's code.  Since someone inspecting your smart contract code won't have access to the call graph, they won't know which way to interpret a method -- maybe it mutates state, or maybe it doesn't.  This makes the developer's life harder since they have to reason about two possible interpretations of their code, instead of one.  I think this is something that we should avoid, since we want code to be as predictable as possible.

**Comment by zone117x** [comment]
Devs can quickly understand aborts and the all-or-nothing mutability consequences in our current system. It conceptually maps to `revert`s in solidity world. 

A `contract-call-readonly` seems more nuanced and easy to make mistakes with. 

Also, the author of a `define-public-readonly` function would benefit from the checker. And consumers would benefits from the explicit intended usage. 

---

However, we still need a new native function for the cross-contract invocation, because `contract-call!` implies mutability. Is `contract-call` (with no `!`) be too confusing? Do we need to define `contract-call-readonly` for at least this purpose anyway?

**Comment by zone117x** [comment]
Would it make sense for `contract-call-readonly` to be able to invoke regular `define` functions, but the type checker verifies that a `contract-call-readonly` can only be used with 'define' functions that do not perform any mutations down the call graph?

**Comment by jcnelson** [comment]
I think `contract-call-readonly!` is fine, and could only call `define-public-readonly` functions.  `contract-call!` could call either.

> Would it make sense for contract-call-readonly to be able to invoke regular define functions, but the type checker verifies that a contract-call-readonly can only be used with 'define' functions that do not perform any mutations down the call graph?

Yes -- this would be the intended behavior.  The set of reachable function calls from `contract-call-readonly` must not include any map mutation functions.  The VM would verify this when it type-checks the contract.

**Comment by kantai** [comment]
Okay, so the decision here is to add:


1. A `(define-public-read-only ...)` construct
2. Either `(contract-call-read-only ...)` or `(contract-call ...)` to indicate that it is calling a read only function

**Comment by zone117x** [comment]
I just realized we didn't figure out the calling convention in https://github.com/blockstack/blockstack-core/pull/966/files

Closing this and open a new issue.
