### ISSUE TITLE
Runtime error type variant

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-core#977]
We should distinguish between interpreter errors that are triggered at runtime versus everything else.  Ideally, these never happen since we want to catch all errors related to the contract being well-formed at deploy-time.

**Comment by kantai** [comment]
I'm not sure what this issue means --

Do you mean, in the interpreter implementation, we should have error classification, so that we can see which errors are "runtime variety"? Or do you mean that the language itself should be able to handle runtime errors (changing the answer to #956)?

Even with enforced null-checks via option types, runtime errors will always be a possibility, e.g., in the event of dividing by zero.

**Comment by jcnelson** [comment]
> Do you mean, in the interpreter implementation, we should have error classification, so that we can see which errors are "runtime variety"?

This interpretation.  Sorry for the ambiguity!

> Even with enforced null-checks via option types, runtime errors will always be a possibility, e.g., in the event of dividing by zero.

Yes, good point.

**Comment by kantai** [comment]
Resolved by #1025
